language: ruby
rvm:
  - 2.2.2
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-2.1.1
  - 1.8.7
  - ree
	
addons:
    code_climate:
        repo_token: 6a3fd6c309eaf9f3b8efdf0b1620b589982250845794a42967866c6915d1af24
